### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-hello-world#24]
this skill does not provide a license

this is recommended as a template for developers, but you did not give explicit authorization to modify it

`When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 
`

https://choosealicense.com/no-permission/

this also impacts end users, since we might not be permitted to use the skill at all

`If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
`

**Comment by krisgesling** [comment]
Thanks for pointing that out - quite an oversight!
